### ISSUE TITLE
cfg 폴더에 coco.names 파일을 추가해야 합니다.

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/AIR-HumanDetector#2]
사용하였을 때 아래와 같은 에러 메시지가 뜹니다.
> FileNotFoundError: [Errno 2] No such file or directory: './cfg/coco.names'  

 cfg 폴더에 coco.names를 추가하여 해결하였습니다.
(coco.names 설치 장소: <https://github.com/pjreddie/darknet/blob/master/data/coco.names>)

**Comment by opo6954** [comment]
> 사용하였을 때 아래와 같은 에러 메시지가 뜹니다.
> 
> > FileNotFoundError: [Errno 2] No such file or directory: './cfg/coco.names'
> 
> cfg 폴더에 coco.names를 추가하여 해결하였습니다.
> (coco.names 설치 장소: https://github.com/pjreddie/darknet/blob/master/data/coco.names)

관련 내용을 업데이트하였습니다.
