### ISSUE TITLE
yolo-f.cfg 에 대한 질문

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/AIR-HumanDetector#3]
Demo.py에서 yolo, yolo-f의 두 모델을 동시에 사용하는데, 두 모델의 차이는 무엇인가요?
 그리고 yolo-f를 학습시킬 때 어떤 data를 사용하셨나요?

**Comment by opo6954** [comment]
관련 기술 개발에 제가 참여하지 않아서 모르겠네요

전임자분에게 연락을 하는 게 좋을 것 같습니다.

박대희(bag2824@gmail.com)

**Comment by kjwoo31** [comment]
박대희 연구원님께 아래와 같이 연락을 받았습니다. 감사합니다.

>안녕하세요.
>
>카이스트 박용화 교수님 연구실에 박대희입니다.
>
>우선 해당 내용은 제 전 담당자인 양현승 교수님 연구실에 박영민 박사님이 수행한 내용입니다.
>
>제가 전달받은 내용으로 알려드리자면,
>
>yolo.cfg는 original paper의 저자가 업로드한 pretrained 파일입니다.
>
>yolo-f.cfg는 1차년도 연구개발내용으로, 추가 데이터셋으로 파인튜닝한 파일입니다.
>
>사용한 추가 데이터는 한국 tv 프로그램 중 고령자가 많이 나오는 동영상 클립 (한국인의 밥상, 궁금한 이야기 Y 등...) 을 직접 어노테이션한 데이터셋입니다. 
>
>따라서 두 모델을 가지고 테스트하실때 최적의 threshold 값도 다르게 설정해주셔야 좋은 결과를 얻을 수 있습니다.
>
>감사합니다.
>
>박대희 드림
